### ISSUE TITLE
How do I add it into a specific location in my 404 page?

### ISSUE THREAD

**Issue by theikell** [theverything/four04kids#11]
If I place the script at the bottom of my markup your widget appears below my footer, I want it above my footer.

If I place the script where I want your widget to appear, it fails to load, I assume because the script is now inside a div.

If I put the script at the bottom of my code and add a div to my page at the location where I want your widget to appear and give the div an id of kids404, my div is moved/removed to the bottom and the widget appears below my footer.

Is it possible to do what I want to do?

**Comment by theverything** [comment]
You are supposed to be able to put the script into your mark up where you want the box to load. No other mark up is needed, just the script.

Is it possible to send a link to your 404 page so I can see the issue?

**Comment by theikell** [comment]
Here is the URL for my 404 page, http://www.karinthy.com/404.aspx

Thanks!

**Comment by theverything** [comment]
@hstove if you get a chance could you look into this.

I visited the 404 page in the link above and in the console I'm getting the following error
`Uncaught NotFoundError: An attempt was made to reference a Node in a context where it does not exist.`

**Comment by hstove** [comment]
Fixed! @theikell , thanks so so much for the bug report! I couldn't figure out why, but `document.body.insertBefore ...` wasn't working in some odd situations. You can see the change in ce8116b57b30e3d03ee23435f3dee75ce21715f1. We now use `insertAdjacentElement`.

**Comment by theikell** [comment]
Great! I've made the background not transparent and added a little extra copy above it. It looks great, thanks so much!

Just FYI, I learned about 404kids at Seattle Startup Weekend. I wanted to join your team but I'm not a rails guy.

BTW, Karinthy is a startup I'm working on. If you can manage the time I'd love your feedback, or at least a Like on my FB page, https://www.facebook.com/KarinthyCommunity

Thanks!

**Comment by theverything** [comment]
No problem thanks for using the script.
