### ISSUE TITLE
404kids dataset doesn't include extra details

### ISSUE THREAD

**Issue by hstove** [theverything/four04kids#2]
There are extra details we don't get from the search API that would be valuable to display. If you open a `kid.missing_url` link, there are some extra fields we could parse.
- height
- eyes
- race
- sex
- weight
- hair
- description

[Example page](http://www.missingkids.com/missingkids/servlet/PubCaseSearchServlet?act=viewPoster&caseNum=1219893&orgPrefix=NCMC)

**Comment by theverything** [comment]
I have a rake task that will grab that info. I was originally using it to find out if the kid had an aged picture. We can modify the rake task to pull in more kid info

**Comment by theverything** [comment]
Added the new data to the json output.
2b7b23c443f7389f9fe146bc15ef40008ad31825
8f70ce7e340b86df6f084e711957c3c56532baf4

**Comment by hstove** [comment]
:+1: :+1: :+1: this is awesome!
