### ISSUE TITLE
github social icon

### ISSUE THREAD

**Issue by hstove** [theverything/four04kids#6]
We should add a github social icon to our links so we can link to this repository. This probably means we should ask Carolyn to create some assets to put there.

![screen shot 2013-09-22 at 2 28 42 am](https://www.evernote.com/shard/s85/sh/ca257918-c16e-405a-ae5d-5c5799813eed/ff86b028e7acbca64517455bb06de880/res/439391a7-0890-4e06-90f1-37cd0d2d74de/skitch.png?resizeSmall&width=832)

**Comment by theverything** [comment]
Add the github icon and converted the social icons into a sprite to help with page loads and the flicker when hovering over the icons.

[The commit](https://github.com/theverything/four04kids/commit/358937b7951752b3489fb464915fe4e5778e0919) is here.
